management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true
server:
  tomcat:
    max-threads: 15
  port: 8082
rating:
  service:
    url: http://localhost:8081/v1/ratings
resilience4j.bulkhead:
  instances:
    ratingService:
      maxConcurrentCalls: 10
      maxWaitDuration: 10ms