version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
  product-service:
    image: product-service-native:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
  product-service-std:
    image: product-service:standard
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongo