spring.cloud.stream:
  function:
    definition: integerProducer
  bindings:
    integerProducer-out-0:
      destination: numbers
      producer:
        use-native-encoding: true
  kafka:
    bindings:
      integerProducer-out-0:
        producer:
          configuration:
            value:
              serializer: org.apache.kafka.common.serialization.IntegerSerializer
    binder:
      brokers:
        - localhost:9092
server.port: 9090
debug: true