apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-scheduler
  name: task-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-scheduler
  template:
    metadata:
      labels:
        app: task-scheduler
    spec:
      containers:
      - image: vinsdocker/task-scheduler
        name: task-scheduler
        env:
        - name: REDIS_HOST
          value: redis-master
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-scheduler
  name: task-scheduler
spec:
  ports:
  - name: task-scheduler
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32001
  selector:
    app: task-scheduler
  type: NodePort  