version: "3"
services:
  mongo1:
    image: mongo
    command: --replSet vinsguru --bind_ip_all
  mongo2:
    image: mongo
    command: --replSet vinsguru --bind_ip_all
  mongo3:
    image: mongo
    command: --replSet vinsguru --bind_ip_all
  init-container:
    image: mongo
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./rs:/rs
    command: ./rs/init.sh
  app:
    build: .
    image: vinsdocker/mongo-replica-set-demo